POST https://9f7xj7y6tk.execute-api.eu-central-1.amazonaws.com/prod/spaces
Content-Type: application/json

{
    "location": "Frankfurt"
}
###

GET https://9f7xj7y6tk.execute-api.eu-central-1.amazonaws.com/prod/spaces
###

GET https://9f7xj7y6tk.execute-api.eu-central-1.amazonaws.com/prod/spaces?id=
###